spring:
  application:
    name: microservice-sso-web

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9101/eureka/,http://peer2:9102/eureka/
      enabled: true
      registerWithEureka: true
      fetchRegistry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

microservice-sso-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  httpclient:
    enabled: true
