spring:
  application:
    name: microservice-sso-service

server:
  port: 8001

# Redis
redisKey:
  # 缓存时间 默认半小时
  expire_time: 1800
  prefix:
    # 用户登录信息前缀
    user_session: 'USER_SESSION:'
    # 验证码Redis前缀
    verifycode: 'VERIFYCODE:'
    # 号码code
    mobile_login_code: 'MOBILE_LOGIN_CODE:'

login:
  # 验证名
  validation:
    #登录名
    ispinengaged: isPinEngaged
    #邮箱
    isemailengaged: isEmailEngaged
    #手机
    ismobileengaged: isMobileEngaged
  # 推荐登录名后缀随机数取值范围
  random_number: 50000
  # 登录成功页面
  success_url: http://localhost:8104/success

druid:
    url: jdbc:mysql://192.168.43.150:3306/dtmp?characterEncoding=utf-8
    driver-class: com.mysql.jdbc.Driver
    username: root
    password: OZo+t9QET+ctzd5Esn9q0GJP5hXtWWIKEsX8c4/w6z4C4AnxrwpvySNgBS89XdazOavjXXZp0oeZtQ3P9lLGEA==
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true
    monitor:
          enabled: false
          druid-stat-view: /druid/*
          druid-web-stat-filter: /*
          allow: 219.230.50.107,127.0.0.1
          deny: 192.168.1.73
          login-username: admin
          login-password: 123456
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
          reset-enable: false
mybatis:
    type-aliases-package: com.alkaid.dtmp.common.pojo
    mapper-locations: classpath:com/alkaid/dtmp/sso/service/mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=count

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9101/eureka/,http://peer2:9102/eureka/
      enabled: true
      registerWithEureka: true
      fetchRegistry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}
    prefer-ip-address: true                         # 设置微服务调用地址为IP优先（缺省为false）
    lease-renewal-interval-in-seconds: 5            # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15        # 发呆时间，即服务续约到期时间（缺省为90s）